# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('willAttend', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('stime', models.DateTimeField()),
                ('etime', models.DateTimeField()),
                ('status', models.IntegerField(choices=[('SCHEDULED', 1), ('RUNNING', 2), ('POST_MEETING', 3), ('FINISHED', 4), ('CANCELLED', 5)])),
            ],
        ),
        migrations.CreateModel(
            name='MeetingWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.CharField(max_length=1024)),
                ('meetingType', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=64)),
                ('recipientType', models.IntegerField(choices=[('User', 1), ('Person', 2)])),
                ('purpose', models.CharField(max_length=128)),
                ('sendDateTime', models.DateTimeField()),
                ('notificationsFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=128)),
                ('qty', models.IntegerField()),
                ('cost', models.FloatField()),
                ('orderDetails', models.CharField(max_length=128)),
                ('isApproved', models.BooleanField()),
                ('prereqFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=64, unique=True)),
                ('capacity', models.IntegerField()),
                ('infrastructure', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.UserProfile'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='hostedAt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Venue'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='ofType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.MeetingWorkflow'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Person'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='meetingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Person'),
        ),
    ]
