# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 6, 16, 48, 32, 61485)),
        ),
    ]
