# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_createdon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='createdOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
