# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20170306_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(choices=[('SCHEDULED', 1), ('RUNNING', 2), ('POST_MEETING', 3), ('FINISHED', 4), ('CANCELLED', 5)], default=1),
        ),
    ]
