# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20170307_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='meetingId',
            new_name='meeting',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='personId',
            new_name='person',
        ),
    ]
