# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_auto_20170311_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='token',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
