# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='isReminded',
            field=models.BooleanField(default=False),
        ),
    ]
